version: '3'
services:
  cassandra-seed-server:
    image: ${CONTAINER_REG}/shr-cassandra-seed-server:latest
    container_name: cassandra-seed
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-server
      - CASSANDRA_CLUSTER_NAME=bdshr
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra/seed-datadir:/var/lib/cassandra

  cassandra-follower-server:
    image: ${CONTAINER_REG}/shr-cassandra-follower-server:latest
    container_name: cassandra-follower
    environment:
      - CASSANDRA_SEEDS=cassandra-seed-server
      - CASSANDRA_CLUSTER_NAME=bdshr
      - CASSANDRA_NUM_TOKENS=256
    volumes:
      - ./cassandra/follower-datadir:/var/lib/cassandra
    depends_on:
      - cassandra-seed-server

  hie-mysql:
    image: mysql:5.6
    restart: always
    container_name: hie-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql/dumps/:/docker-entrypoint-initdb.d/
      - ./mysql/mysql-datadir:/var/lib/mysql

  identity-server:
    image: ${CONTAINER_REG}/shr-identity-server
    container_name: identity-server
    ports:
      - "8084:8084"

  healthid-server:
    image: ${CONTAINER_REG}/shr-healthid-server:latest
    container_name: healthid-server
    ports:
      - "8086:8086"
    depends_on:
      - cassandra-follower-server

  mci-server:
    image: ${CONTAINER_REG}/shr-mci-server:latest
    container_name: mci-server
    ports:
      - "8081:8081"
    depends_on:
      - cassandra-follower-server

  shr-server:
    image: ${CONTAINER_REG}/shr-server:latest
    container_name: shr-server
    ports:
      - "8082:8082"
    depends_on:
      - cassandra-follower-server

  tr-server:
    image: ${CONTAINER_REG}/shr-tr-server:latest
    container_name: tr-server
    ports:
      - "9080:9080"
    depends_on:
      - hie-mysql

  datasense:
    image: ${CONTAINER_REG}/datasense-server:latest
    container_name: datasense-server
    ports:
      - "8083:8083"
    depends_on:
      - hie-mysql
  
